name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ocaml-version: [ '4.14.0' ]

    steps:
    - uses: actions/checkout@v4
    - name: Setup OCaml ${{ matrix.ocaml-version }}
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: ${{ matrix.ocaml-version }}
    - name: Build
      run: |
        opam install -y dune core_kernel clap ppx_deriving ppx_deriving_yojson ppxlib yojson fileutils yaml
        eval $(opam env)
        dune build @install
        mkdir -p output
        dune install --prefix output
    - name: Prepare to test
      run: |
        sudo apt-get install -y lua5.3 lua5.1
        mkdir -p test/out
    - name: Test (Lua 5.3)
      run: ./test/run-test.py -b output/bin/moonsmith -l lua5.3 -n 2500 -t 2
    - name: Test (Lua 5.1)
      run: |
        cp moonsmith-lua51.yml moonsmith.yml
        ./test/run-test.py -b output/bin/moonsmith -l lua5.1 -n 2500 -t 2
